### ISSUE TITLE
Bright Green? Bright Yellow? Bright Blue? Bright Magenta? Bright Cyan?

### ISSUE THREAD

**Issue by LoganDark** [tamul/solarized-osx-terminal-colors#1]
![What?](https://cloud.githubusercontent.com/assets/4723091/24319818/ab90b40e-10e4-11e7-843a-0c0d78bf080a.png)
What?

**Comment by mtayler** [comment]
Are you asking about why the colours don't match the names or what's your question? It's really not clear what you're asking.

**Comment by LoganDark** [comment]
> why the colours don't match the names

Isn't that obvious? Should I edit the OP?

But yes, that is the question.

**Comment by mtayler** [comment]
1. You're coming off as condescending on a topic you're asking a question about. I thought twice about actually answering you: if you ask questions with more tact they're more likely to get answered.

2. This is due to how the terminal handles color schemes. The naming is essentially a suggestion: if you use the default colorscheme in, for example, vim, while using solarized as your terminal color scheme, vim will use colours assuming they are similar to the name and you'll get a weird colorscheme. As seen here the solarized colorscheme ignores the "suggested" arrangement; partly, I believe, to accomplish having the same contrast between the light and dark background.
